package store

import (
	"time"

	"github.com/stanleyHayes/nadaa/services/shelter-service/internal/models"
)

func seedShelters(now time.Time) []models.Shelter {
	return []models.Shelter{
		{
			ID:               "00000000-0000-0000-0000-000000000301",
			Name:             "Accra Metro Assembly Shelter",
			Type:             "evacuation_shelter",
			Region:           "Greater Accra",
			District:         "Accra Metropolitan",
			Address:          "Accra Metropolitan Assembly Hall",
			Location:         models.Coordinates{Lat: 5.560, Lng: -0.200},
			Capacity:         450,
			CurrentOccupancy: 116,
			Status:           "open",
			Contact:          "112",
			Facilities:       []string{"water", "first_aid", "accessible_entry", "family_area"},
			Notes:            "Primary flood evacuation shelter for central Accra.",
			UpdatedAt:        now,
		},
		{
			ID:               "00000000-0000-0000-0000-000000000302",
			Name:             "Osu Community Hall",
			Type:             "temporary_shelter",
			Region:           "Greater Accra",
			District:         "Korle Klottey",
			Address:          "Osu Community Hall",
			Location:         models.Coordinates{Lat: 5.550, Lng: -0.180},
			Capacity:         220,
			CurrentOccupancy: 34,
			Status:           "open",
			Contact:          "112",
			Facilities:       []string{"water", "first_aid", "family_area"},
			Notes:            "Suitable for short-term shelter and reunification.",
			UpdatedAt:        now,
		},
		{
			ID:               "00000000-0000-0000-0000-000000000303",
			Name:             "Kaneshie Social Centre",
			Type:             "relief_shelter",
			Region:           "Greater Accra",
			District:         "Okaikwei South",
			Address:          "Kaneshie Market Road",
			Location:         models.Coordinates{Lat: 5.566, Lng: -0.242},
			Capacity:         180,
			CurrentOccupancy: 180,
			Status:           "full",
			Contact:          "112",
			Facilities:       []string{"water", "food_distribution"},
			Notes:            "At capacity; redirect new arrivals unless occupancy changes.",
			UpdatedAt:        now,
		},
	}
}

func seedRecovery(now time.Time) []models.RecoverySupportLocation {
	return []models.RecoverySupportLocation{
		{
			ID:        "recovery_ama_relief_001",
			Name:      "AMA Relief Distribution Point",
			Type:      "relief_point",
			Region:    "Greater Accra",
			District:  "Accra Metropolitan",
			Address:   "Independence Avenue recovery desk",
			Location:  models.Coordinates{Lat: 5.558, Lng: -0.197},
			Contact:   "112",
			Services:  []string{"food", "water", "blankets", "family_reunification"},
			Hours:     "08:00-20:00",
			Status:    "open",
			UpdatedAt: now,
		},
		{
			ID:        "recovery_korle_bu_medical_001",
			Name:      "Korle Bu Emergency Stabilization Desk",
			Type:      "medical_support",
			Region:    "Greater Accra",
			District:  "Accra Metropolitan",
			Address:   "Korle Bu emergency entrance",
			Location:  models.Coordinates{Lat: 5.536, Lng: -0.227},
			Contact:   "112",
			Services:  []string{"first_aid", "triage", "medical_referral"},
			Hours:     "24 hours",
			Status:    "open",
			UpdatedAt: now,
		},
		{
			ID:        "recovery_osu_registration_001",
			Name:      "Osu Recovery Registration Desk",
			Type:      "recovery_registration",
			Region:    "Greater Accra",
			District:  "Korle Klottey",
			Address:   "Osu Community Hall annex",
			Location:  models.Coordinates{Lat: 5.551, Lng: -0.181},
			Contact:   "112",
			Services:  []string{"needs_registration", "damage_reporting", "case_follow_up"},
			Hours:     "08:00-18:00",
			Status:    "open",
			UpdatedAt: now,
		},
	}
}

func seedHospitals(now time.Time) []models.HospitalCapacity {
	return []models.HospitalCapacity{
		{
			ID:                     "hospital_001",
			Name:                   "Korle Bu Teaching Hospital",
			Type:                   "teaching_hospital",
			Region:                 "Greater Accra",
			District:               "Accra Metropolitan",
			Address:                "Korle Bu emergency entrance",
			Location:               models.Coordinates{Lat: 5.536, Lng: -0.227},
			Contact:                "0302665401",
			Services:               []string{"emergency", "trauma", "icu", "maternity", "pediatric", "oxygen"},
			TotalBeds:              820,
			AvailableBeds:          46,
			ICUBedsAvailable:       4,
			MaternityBedsAvailable: 9,
			PediatricBedsAvailable: 5,
			IsolationBedsAvailable: 3,
			EmergencyCapacity:      "available",
			EmergencyUnitStatus:    "open",
			AmbulancesAvailable:    3,
			OxygenAvailable:        true,
			Notes:                  "Major referral facility for Accra emergency transfers.",
			Source:                 "fixture",
			SourceRef:              "hospital-capacity-feed",
			UpdatedAt:              now,
		},
		{
			ID:                     "hospital_002",
			Name:                   "Greater Accra Regional Hospital",
			Type:                   "regional_hospital",
			Region:                 "Greater Accra",
			District:               "Accra Metropolitan",
			Address:                "Ridge Hospital emergency unit",
			Location:               models.Coordinates{Lat: 5.563, Lng: -0.191},
			Contact:                "0302425201",
			Services:               []string{"emergency", "trauma", "oxygen", "ambulance"},
			TotalBeds:              420,
			AvailableBeds:          12,
			ICUBedsAvailable:       1,
			MaternityBedsAvailable: 3,
			PediatricBedsAvailable: 2,
			IsolationBedsAvailable: 0,
			EmergencyCapacity:      "limited",
			EmergencyUnitStatus:    "busy",
			AmbulancesAvailable:    1,
			OxygenAvailable:        true,
			Notes:                  "Emergency unit busy; use for critical stabilization.",
			Source:                 "fixture",
			SourceRef:              "hospital-capacity-feed",
			UpdatedAt:              now.Add(-12 * time.Minute),
		},
		{
			ID:                     "hospital_003",
			Name:                   "Tema General Hospital",
			Type:                   "general_hospital",
			Region:                 "Greater Accra",
			District:               "Tema Metropolitan",
			Address:                "Tema Community 12",
			Location:               models.Coordinates{Lat: 5.669, Lng: -0.016},
			Contact:                "0303202231",
			Services:               []string{"emergency", "maternity", "pediatric", "ambulance"},
			TotalBeds:              310,
			AvailableBeds:          0,
			ICUBedsAvailable:       0,
			MaternityBedsAvailable: 1,
			PediatricBedsAvailable: 0,
			IsolationBedsAvailable: 0,
			EmergencyCapacity:      "full",
			EmergencyUnitStatus:    "divert",
			AmbulancesAvailable:    0,
			OxygenAvailable:        false,
			Notes:                  "Capacity stale; confirm before transfer.",
			Source:                 "fixture",
			SourceRef:              "hospital-capacity-feed",
			UpdatedAt:              now.Add(-45 * time.Minute),
		},
	}
}

func seedReliefPoints(now time.Time) []models.ReliefPoint {
	return []models.ReliefPoint{
		{
			ID:             "relief_ama_food_001",
			Name:           "AMA Central Food Distribution",
			Type:           "food",
			Region:         "Greater Accra",
			District:       "Accra Metropolitan",
			Address:        "Independence Avenue, Accra",
			Location:       models.Coordinates{Lat: 5.560, Lng: -0.200},
			Contact:        "0302112233",
			OperatingHours: "08:00-18:00",
			Eligibility:    "Open to households affected by flooding.",
			Schedule:       "Daily",
			StockCategories: []models.ReliefStockCategory{
				{Category: "rice_kg", Quantity: 500, Unit: "kg", LastUpdated: now},
				{Category: "water_bottles", Quantity: 1200, Unit: "bottles", LastUpdated: now},
			},
			Status:    "open",
			Source:    "manual",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			ID:             "relief_kaneshie_water_001",
			Name:           "Kaneshie Water Relief Point",
			Type:           "water",
			Region:         "Greater Accra",
			District:       "Okaikwei South",
			Address:        "Kaneshie Market Road",
			Location:       models.Coordinates{Lat: 5.566, Lng: -0.242},
			Contact:        "112",
			OperatingHours: "06:00-22:00",
			Eligibility:    "Residents in flood-affected zones.",
			Schedule:       "Daily",
			StockCategories: []models.ReliefStockCategory{
				{Category: "water_bottles", Quantity: 800, Unit: "bottles", LastUpdated: now},
				{Category: "water_sachets", Quantity: 2000, Unit: "sachets", LastUpdated: now},
			},
			Status:    "limited",
			Source:    "manual",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			ID:             "relief_madina_mixed_001",
			Name:           "Madina Emergency Relief Hub",
			Type:           "mixed",
			Region:         "Greater Accra",
			District:       "La Nkwantanang Madina",
			Address:        "Madina Zongo Junction",
			Location:       models.Coordinates{Lat: 5.680, Lng: -0.160},
			Contact:        "0302445566",
			OperatingHours: "07:00-19:00",
			Eligibility:    "Displaced families and vulnerable groups.",
			Schedule:       "Daily",
			StockCategories: []models.ReliefStockCategory{
				{Category: "blankets", Quantity: 150, Unit: "units", LastUpdated: now},
				{Category: "hygiene_kits", Quantity: 80, Unit: "kits", LastUpdated: now},
				{Category: "water_bottles", Quantity: 300, Unit: "bottles", LastUpdated: now},
			},
			Status:    "open",
			Source:    "manual",
			CreatedAt: now,
			UpdatedAt: now,
		},
	}
}

func seedAidRequests(now time.Time) []models.AidRequest {
	return []models.AidRequest{
		{
			ID:                    "aid_ama_hygiene_001",
			Title:                 "Hygiene kits for displaced households",
			Category:              "hygiene",
			Priority:              "high",
			Status:                "open",
			Region:                "Greater Accra",
			District:              "Accra Metropolitan",
			Location:              models.Coordinates{Lat: 5.560, Lng: -0.200},
			ReceivingOrganization: "AMA Central Food Distribution",
			Contact:               "0302112233",
			QuantityNeeded:        300,
			QuantityUnit:          "kits",
			QuantityPledged:       80,
			Description:           "Hygiene kits for families temporarily staying around the central distribution point.",
			NeededBy:              now.Add(72 * time.Hour),
			Visibility:            "public",
			SourceReliefPointID:   "relief_ama_food_001",
			CreatedBy:             "usr_relief_fixture",
			ApprovedBy:            "usr_relief_fixture",
			ApprovalNotes:         "Verified by district relief desk.",
			AntiFraudNotes:        "Receiving organization and point contact confirmed.",
			CreatedAt:             now,
			UpdatedAt:             now,
		},
		{
			ID:                    "aid_madina_water_001",
			Title:                 "Water sachets for Madina relief hub",
			Category:              "water",
			Priority:              "urgent",
			Status:                "pending_review",
			Region:                "Greater Accra",
			District:              "La Nkwantanang Madina",
			Location:              models.Coordinates{Lat: 5.680, Lng: -0.160},
			ReceivingOrganization: "Madina Emergency Relief Hub",
			Contact:               "0302445566",
			QuantityNeeded:        5000,
			QuantityUnit:          "sachets",
			Description:           "Requested water support for displaced families arriving from low-lying areas.",
			NeededBy:              now.Add(48 * time.Hour),
			Visibility:            "partners_only",
			SourceReliefPointID:   "relief_madina_mixed_001",
			AgencyID:              "00000000-0000-0000-0000-000000000204",
			CreatedBy:             "usr_relief_fixture",
			CreatedAt:             now,
			UpdatedAt:             now,
		},
	}
}

func seedAidPledges(now time.Time) []models.AidPledge {
	return []models.AidPledge{
		{
			ID:               "pledge_hygiene_001",
			AidRequestID:     "aid_ama_hygiene_001",
			DonorName:        "Accra Mutual Aid Network",
			DonorType:        "ngo",
			Contact:          "aiddesk@example.org",
			Quantity:         80,
			Unit:             "kits",
			Note:             "Delivery available within 24 hours after acceptance.",
			Status:           "accepted",
			ReviewStatus:     "cleared",
			FraudReviewNotes: "Known partner; contact verified.",
			ReviewedBy:       "usr_relief_fixture",
			PledgedAt:        now,
			UpdatedAt:        now,
		},
	}
}
