import { nadaaBrand } from "@nadaa/brand";
import type {
  AlertSeverity,
  AlertTargetType,
  AuthorityAlertRecord,
  Coordinates,
  IncidentStatus,
  RiskLevel,
  ShelterRecord,
} from "@nadaa/shared-types";
import type {
  AssignmentAgencyOption,
  CommandIncident,
  FilterState,
} from "./types";

export const assignmentAgencyOptions: AssignmentAgencyOption[] = [
  {
    id: "00000000-0000-0000-0000-000000000101",
    name: "NADMO Accra Metro",
    type: "nadmo",
    responderLead: "NADMO Duty Officer",
  },
  {
    id: "00000000-0000-0000-0000-000000000201",
    name: "Ghana National Fire Service",
    type: "fire",
    responderLead: "Station Officer Mensah",
  },
  {
    id: "00000000-0000-0000-0000-000000000202",
    name: "National Ambulance Service",
    type: "ambulance",
    responderLead: "Ambulance Control Lead",
  },
  {
    id: "00000000-0000-0000-0000-000000000203",
    name: "Ghana Police Service",
    type: "police",
    responderLead: "Motor Traffic Lead",
  },
  {
    id: "00000000-0000-0000-0000-000000000204",
    name: "Accra Metropolitan Assembly",
    type: "district_assembly",
    responderLead: "Metro Works Supervisor",
  },
];

const shelterFixtureUpdatedAt = "2026-07-06T12:00:00Z";

export const fallbackShelters: ShelterRecord[] = [
  {
    id: "00000000-0000-0000-0000-000000000301",
    name: "Accra Metro Assembly Shelter",
    type: "evacuation_shelter",
    region: "Greater Accra",
    district: "Accra Metropolitan",
    address: "Accra Metropolitan Assembly Hall",
    location: { lat: 5.56, lng: -0.2 },
    capacity: 450,
    currentOccupancy: 116,
    status: "open",
    contact: "112",
    facilities: ["water", "first_aid", "accessible_entry", "family_area"],
    notes: "Primary flood evacuation shelter for central Accra.",
    updatedAt: shelterFixtureUpdatedAt,
  },
  {
    id: "00000000-0000-0000-0000-000000000302",
    name: "Osu Community Hall",
    type: "temporary_shelter",
    region: "Greater Accra",
    district: "Korle Klottey",
    address: "Osu Community Hall",
    location: { lat: 5.55, lng: -0.18 },
    capacity: 220,
    currentOccupancy: 34,
    status: "open",
    contact: "112",
    facilities: ["water", "first_aid", "family_area"],
    notes: "Short-term shelter and reunification point.",
    updatedAt: shelterFixtureUpdatedAt,
  },
  {
    id: "00000000-0000-0000-0000-000000000303",
    name: "Kaneshie Social Centre",
    type: "relief_shelter",
    region: "Greater Accra",
    district: "Okaikwei South",
    address: "Kaneshie Market Road",
    location: { lat: 5.566, lng: -0.242 },
    capacity: 180,
    currentOccupancy: 180,
    status: "full",
    contact: "112",
    facilities: ["water", "food_distribution"],
    notes: "At capacity; redirect new arrivals unless occupancy changes.",
    updatedAt: shelterFixtureUpdatedAt,
  },
];

export const fallbackIncidents: CommandIncident[] = [
  {
    id: "inc_accra_flood_0241",
    reference: "INC-0241",
    type: "flood",
    severity: "severe",
    status: "under_review",
    description:
      "Water is rising near a low-lying road and vehicles are trapped.",
    location: { lat: 5.579, lng: -0.212 },
    peopleAffected: 28,
    injuriesReported: false,
    urgency: "life_threatening",
    anonymous: false,
    contactPermission: true,
    media: ["media_flood_photo_001"],
    priorityReview: true,
    abuseSignals: [
      {
        code: "reporter_burst",
        label: "Reporter burst",
        detail: "Reporter has submitted multiple nearby reports today.",
        weight: 0.55,
      },
    ],
    abuseScore: 0.55,
    abuseReviewRequired: true,
    abuseReviewReason: "Review requested: Reporter burst",
    duplicateCandidates: [
      {
        incidentId: "inc_accra_flood_0237",
        reference: "INC-0237",
        score: 0.82,
        distanceMeters: 214,
        minutesApart: 16,
        reasons: ["same_hazard", "nearby_location", "recent_report"],
      },
    ],
    mergedIncidentIds: [],
    assignments: [],
    timeline: [],
    reportedBy: { userId: "usr_ama", phone: "+233200000003" },
    createdAt: "2026-07-06T18:42:00Z",
    updatedAt: "2026-07-06T18:48:00Z",
    region: "Greater Accra",
    district: "Accra Metropolitan",
    locality: "Accra Central",
    assignedAgency: "Unassigned",
    responderEta: "7 min",
    timelineEntries: [
      "Citizen report received with photo evidence",
      "Duplicate reports grouped near Accra Central",
      "NADMO AMA dispatcher reviewing severity",
    ],
    source: "fixture",
  },
  {
    id: "inc_accra_flood_0237",
    reference: "INC-0237",
    type: "flood",
    severity: "high",
    status: "reported",
    description:
      "Resident reports the same market road flooding with stranded taxis.",
    location: { lat: 5.579, lng: -0.212 },
    peopleAffected: 9,
    injuriesReported: false,
    urgency: "high",
    anonymous: false,
    contactPermission: true,
    media: [],
    priorityReview: true,
    abuseSignals: [],
    abuseScore: 0,
    abuseReviewRequired: false,
    duplicateCandidates: [
      {
        incidentId: "inc_accra_flood_0241",
        reference: "INC-0241",
        score: 0.82,
        distanceMeters: 214,
        minutesApart: 16,
        reasons: ["same_hazard", "nearby_location", "recent_report"],
      },
    ],
    mergedIncidentIds: [],
    assignments: [],
    timeline: [],
    reportedBy: { userId: "usr_kofi", phone: "+233200000004" },
    createdAt: "2026-07-06T18:26:00Z",
    updatedAt: "2026-07-06T18:43:00Z",
    region: "Greater Accra",
    district: "Accra Metropolitan",
    locality: "Accra Central",
    assignedAgency: "Unassigned",
    responderEta: "12 min",
    timelineEntries: [
      "Citizen report received near market road",
      "Matched as likely duplicate of INC-0241",
      "Awaiting dispatcher merge review",
    ],
    source: "fixture",
  },
  {
    id: "inc_tema_crash_0239",
    reference: "INC-0239",
    type: "road_crash",
    severity: "high",
    status: "assigned",
    description: "Three-vehicle crash blocking the Tema motorway shoulder.",
    location: { lat: 5.642, lng: -0.028 },
    peopleAffected: 11,
    injuriesReported: true,
    urgency: "high",
    anonymous: false,
    contactPermission: true,
    media: ["media_crash_photo_002"],
    priorityReview: true,
    abuseSignals: [],
    abuseScore: 0,
    abuseReviewRequired: false,
    duplicateCandidates: [],
    mergedIncidentIds: [],
    assignments: [
      {
        id: "asg_fixture_tema",
        agencyId: "00000000-0000-0000-0000-000000000202",
        agencyName: "National Ambulance Service",
        agencyType: "ambulance",
        priority: "high",
        instructions: "Attend crash scene and coordinate casualty transport.",
        responderLead: "Ambulance Control Lead",
        status: "active",
        assignedBy: "usr_dispatcher_fixture",
        assignedAt: "2026-07-06T18:33:00Z",
      },
    ],
    timeline: [],
    createdAt: "2026-07-06T18:25:00Z",
    updatedAt: "2026-07-06T18:39:00Z",
    region: "Greater Accra",
    district: "Tema Metropolitan",
    locality: "Tema Motorway",
    assignedAgency: "National Ambulance Service",
    responderEta: "12 min",
    timelineEntries: [
      "Dispatcher verified multiple injured persons",
      "Ambulance and police units assigned",
      "Motorway patrol requested lane control",
    ],
    source: "fixture",
  },
  {
    id: "inc_ablekuma_drain_0236",
    reference: "INC-0236",
    type: "blocked_drain",
    severity: "moderate",
    status: "verified",
    description: "Blocked drain backing water into a residential street.",
    location: { lat: 5.601, lng: -0.286 },
    peopleAffected: 14,
    injuriesReported: false,
    urgency: "moderate",
    anonymous: true,
    contactPermission: false,
    media: [],
    priorityReview: false,
    abuseSignals: [],
    abuseScore: 0,
    abuseReviewRequired: false,
    duplicateCandidates: [],
    mergedIncidentIds: [],
    assignments: [],
    timeline: [],
    createdAt: "2026-07-06T17:58:00Z",
    updatedAt: "2026-07-06T18:12:00Z",
    region: "Greater Accra",
    district: "Ablekuma West",
    locality: "Dansoman",
    assignedAgency: "Ready for assignment",
    responderEta: "31 min",
    timelineEntries: [
      "District officer verified blocked drain",
      "Sanitation crew notified",
      "Resident contact hidden due anonymous report",
    ],
    source: "fixture",
  },
  {
    id: "inc_korle_fire_0232",
    reference: "INC-0232",
    type: "fire",
    severity: "high",
    status: "response_en_route",
    description: "Electrical fire reported behind a market stall.",
    location: { lat: 5.544, lng: -0.213 },
    peopleAffected: 8,
    injuriesReported: false,
    urgency: "high",
    anonymous: false,
    contactPermission: true,
    media: ["media_fire_photo_003"],
    priorityReview: true,
    abuseSignals: [],
    abuseScore: 0,
    abuseReviewRequired: false,
    duplicateCandidates: [],
    mergedIncidentIds: [],
    assignments: [
      {
        id: "asg_fixture_fire",
        agencyId: "00000000-0000-0000-0000-000000000201",
        agencyName: "Ghana National Fire Service",
        agencyType: "fire",
        priority: "urgent",
        instructions: "Dispatch engine crew and secure hydrant access.",
        responderLead: "Station Officer Mensah",
        status: "active",
        assignedBy: "usr_dispatcher_fixture",
        assignedAt: "2026-07-06T18:05:00Z",
      },
    ],
    timeline: [],
    createdAt: "2026-07-06T17:41:00Z",
    updatedAt: "2026-07-06T18:19:00Z",
    region: "Greater Accra",
    district: "Accra Metropolitan",
    locality: "Korle Gonno",
    assignedAgency: "Ghana National Fire Service",
    responderEta: "5 min",
    timelineEntries: [
      "Fire service call confirmed smoke visible",
      "Hydrant access checked by dispatcher",
      "Engine crew en route",
    ],
    source: "fixture",
  },
];

export const fallbackAlerts: AuthorityAlertRecord[] = [
  {
    id: "alert_fixture_submitted",
    title: "Accra flood watch",
    hazardType: "flood",
    severity: "warning",
    message: "Heavy rainfall may cause flooding in low-lying communities.",
    target: {
      type: "district",
      ids: ["accra-metropolitan"],
      label: "Accra Metropolitan",
    },
    startsAt: "2026-07-06T19:30:00Z",
    expiresAt: "2026-07-07T07:00:00Z",
    recommendedAction:
      "Avoid flooded roads and prepare to move to higher ground.",
    evacuationRequired: false,
    shelterIds: ["00000000-0000-0000-0000-000000000301"],
    issuingAgencyId: "00000000-0000-0000-0000-000000000101",
    issuedBy: "usr_dispatcher_fixture",
    status: "submitted",
    emergencyOverride: false,
    createdAt: "2026-07-06T18:15:00Z",
    updatedAt: "2026-07-06T18:45:00Z",
    submittedAt: "2026-07-06T18:45:00Z",
  },
];

export const defaultFilters: FilterState = {
  hazard: "all",
  regionDistrict: "all",
  severity: "all",
  status: "all",
  time: "all",
};

export const severityOrder: Record<RiskLevel, number> = {
  emergency: 5,
  severe: 4,
  high: 3,
  moderate: 2,
  low: 1,
};

export const severityColors: Record<RiskLevel, string> = {
  emergency: "#7F1D1D",
  severe: nadaaBrand.colors.red,
  high: "#D97706",
  moderate: nadaaBrand.colors.gold,
  low: nadaaBrand.colors.green,
};

export const alertSeverityOptions: AlertSeverity[] = [
  "advisory",
  "watch",
  "warning",
  "severe_warning",
  "emergency",
];

export const alertTargetTypeOptions: AlertTargetType[] = [
  "district",
  "radius",
  "custom",
  "region",
  "community",
  "national",
];

export type AlertTargetCatalogItem = {
  id: string;
  type: AlertTargetType;
  label: string;
  center: Coordinates;
  radiusMeters: number;
  areaSqKm: number;
  estimatedPopulation: number;
};

export const alertTargetCatalog: Record<string, AlertTargetCatalogItem> = {
  "region:greater-accra": {
    id: "greater-accra",
    type: "region",
    label: "Greater Accra Region",
    center: { lat: 5.75, lng: -0.11 },
    radiusMeters: 52000,
    areaSqKm: 3245,
    estimatedPopulation: 5455000,
  },
  "district:accra-metropolitan": {
    id: "accra-metropolitan",
    type: "district",
    label: "Accra Metropolitan",
    center: { lat: 5.56, lng: -0.2 },
    radiusMeters: 9000,
    areaSqKm: 61,
    estimatedPopulation: 284000,
  },
  "district:tema-metropolitan": {
    id: "tema-metropolitan",
    type: "district",
    label: "Tema Metropolitan",
    center: { lat: 5.642, lng: -0.028 },
    radiusMeters: 12000,
    areaSqKm: 565,
    estimatedPopulation: 402000,
  },
  "district:ablekuma-west": {
    id: "ablekuma-west",
    type: "district",
    label: "Ablekuma West",
    center: { lat: 5.601, lng: -0.286 },
    radiusMeters: 7000,
    areaSqKm: 15,
    estimatedPopulation: 220000,
  },
  "community:accra-central": {
    id: "accra-central",
    type: "community",
    label: "Accra Central",
    center: { lat: 5.556, lng: -0.202 },
    radiusMeters: 3000,
    areaSqKm: 8,
    estimatedPopulation: 75000,
  },
};

export const incidentStatusOptions: IncidentStatus[] = [
  "reported",
  "under_review",
  "verified",
  "assigned",
  "response_en_route",
  "on_scene",
  "contained",
  "recovery_ongoing",
  "closed",
  "false_report",
];

export const incidentTransitionOptions: Record<
  IncidentStatus,
  IncidentStatus[]
> = {
  reported: ["under_review", "verified", "false_report"],
  under_review: ["verified", "false_report"],
  verified: ["assigned", "response_en_route", "false_report"],
  assigned: [
    "response_en_route",
    "on_scene",
    "contained",
    "recovery_ongoing",
    "closed",
    "false_report",
  ],
  response_en_route: [
    "on_scene",
    "contained",
    "recovery_ongoing",
    "closed",
    "false_report",
  ],
  on_scene: ["contained", "recovery_ongoing", "closed", "false_report"],
  contained: ["recovery_ongoing", "closed", "false_report"],
  recovery_ongoing: ["closed", "false_report"],
  closed: [],
  false_report: [],
};
