import type { AuditLogRecord } from "@nadaa/shared-types";
import type {
  AdminUserFormState,
  AlertRuleSummary,
  DataSourceSummary,
  ManagedAgency,
  ManagedAgencyUser,
} from "./types";

const now = "2026-07-06T12:00:00Z";

export const fallbackAgencies: ManagedAgency[] = [
  {
    id: "00000000-0000-0000-0000-000000000101",
    name: "NADMO National Operations",
    type: "nadmo",
    region: "National",
    district: "Headquarters",
    contactNumber: "112",
    status: "active",
    users: 8,
    openAssignments: 4,
    mfaCoverage: 100,
    dataScope: "National coordination, alert approval, audit review",
    lastAuditAt: "2026-07-06T11:42:00Z",
  },
  {
    id: "00000000-0000-0000-0000-000000000102",
    name: "NADMO Accra Metro",
    type: "district_assembly",
    region: "Greater Accra",
    district: "Accra Metropolitan",
    contactNumber: "+233302000112",
    status: "active",
    users: 12,
    openAssignments: 9,
    mfaCoverage: 92,
    dataScope: "District command, incident verification, shelter updates",
    lastAuditAt: "2026-07-06T10:58:00Z",
  },
  {
    id: "00000000-0000-0000-0000-000000000103",
    name: "Ghana Fire Service - Greater Accra",
    type: "fire",
    region: "Greater Accra",
    district: "Accra Metropolitan",
    contactNumber: "192",
    status: "active",
    users: 6,
    openAssignments: 3,
    mfaCoverage: 83,
    dataScope: "Response assignments, operational notes, fire incidents",
    lastAuditAt: "2026-07-06T09:40:00Z",
  },
  {
    id: "00000000-0000-0000-0000-000000000104",
    name: "Ghana Meteorological Agency",
    type: "meteorological",
    region: "National",
    district: "Headquarters",
    contactNumber: "+233302000444",
    status: "pilot",
    users: 4,
    openAssignments: 0,
    mfaCoverage: 75,
    dataScope: "Weather observation imports and rainfall warning signals",
    lastAuditAt: "2026-07-06T08:35:00Z",
  },
];

export const fallbackUsers: ManagedAgencyUser[] = [
  {
    id: "usr_system_admin",
    name: "NADAA System Admin",
    email: "admin@nadaa.local",
    phone: "+233200000001",
    role: "system_admin",
    agency: fallbackAgencies[0],
    mfaRequired: true,
    mfaEnabled: true,
    createdAt: "2026-07-06T08:00:00Z",
    updatedAt: "2026-07-06T08:03:00Z",
    status: "active",
    lastLoginAt: "2026-07-06T11:49:00Z",
    accessScope: "Platform governance",
  },
  {
    id: "usr_agency_admin_accra",
    name: "Accra Agency Admin",
    email: "agency.admin@nadaa.local",
    phone: "+233200000002",
    role: "agency_admin",
    agency: fallbackAgencies[1],
    mfaRequired: true,
    mfaEnabled: true,
    createdAt: "2026-07-06T08:10:00Z",
    updatedAt: "2026-07-06T08:15:00Z",
    status: "active",
    lastLoginAt: "2026-07-06T10:50:00Z",
    accessScope: "Accra Metropolitan agency scope",
  },
  {
    id: "usr_dispatcher_accra",
    name: "Accra Dispatcher",
    email: "dispatcher@nadaa.local",
    phone: "+233200000003",
    role: "dispatcher",
    agency: fallbackAgencies[1],
    mfaRequired: true,
    mfaEnabled: true,
    createdAt: "2026-07-06T08:20:00Z",
    updatedAt: "2026-07-06T08:23:00Z",
    status: "active",
    lastLoginAt: "2026-07-06T11:30:00Z",
    accessScope: "Incident command only",
  },
  {
    id: "usr_gmet_observer",
    name: "GMet Duty Officer",
    email: "gmet@nadaa.local",
    phone: "+233200000004",
    role: "agency_viewer",
    agency: fallbackAgencies[3],
    mfaRequired: true,
    mfaEnabled: false,
    createdAt: "2026-07-06T08:28:00Z",
    updatedAt: "2026-07-06T08:28:00Z",
    status: "mfa_pending",
    accessScope: "Weather integration visibility",
  },
];

export const fallbackAuditLogs: AuditLogRecord[] = [
  {
    id: "aud_admin_viewed",
    actorUserId: "usr_system_admin",
    actorAgencyId: fallbackAgencies[0].id,
    actorRole: "system_admin",
    action: "audit.logs.viewed",
    targetType: "audit_logs",
    requestId: "req-admin-console",
    ipAddress: "203.0.113.10",
    userAgent: "nadaa-admin-web",
    after: { limit: 25 },
    createdAt: now,
  },
  {
    id: "aud_agency_user_created",
    actorUserId: "usr_system_admin",
    actorAgencyId: fallbackAgencies[0].id,
    actorRole: "system_admin",
    action: "auth.agency_user.created",
    targetType: "agency_user",
    targetId: "usr_gmet_observer",
    requestId: "req-create-gmet",
    after: {
      role: "agency_viewer",
      agencyId: fallbackAgencies[3].id,
      mfaRequired: true,
      mfaEnabled: false,
    },
    createdAt: "2026-07-06T08:28:00Z",
  },
  {
    id: "aud_alert_approved",
    actorUserId: "usr_system_admin",
    actorAgencyId: fallbackAgencies[0].id,
    actorRole: "system_admin",
    action: "alert.approved",
    targetType: "alert",
    targetId: "alert_fixture_submitted",
    requestId: "req-alert-approval",
    after: { severity: "warning", targetType: "district" },
    createdAt: "2026-07-06T07:54:00Z",
  },
];

export const fallbackDataSources: DataSourceSummary[] = [
  {
    id: "gmet-rainfall-nowcast",
    partner: "Ghana Meteorological Agency",
    domain: "weather",
    direction: "inbound",
    status: "mock_contract",
    cadence: "Every 15 minutes during watch/warning periods",
    freshnessWindowMinutes: 30,
    pii: "none",
    authenticationMode: "api_key",
    secretScope: "environment_secret_manager",
    owner: "GMet",
    manualFallback:
      "Duty officer can upload rainfall bulletin into dispatch notes.",
    updatedAt: now,
  },
  {
    id: "hydro-water-level",
    partner: "Hydrological Services Department",
    domain: "hydrology",
    direction: "inbound",
    status: "mock_contract",
    cadence: "Hourly during rainy season",
    freshnessWindowMinutes: 60,
    pii: "none",
    authenticationMode: "signed_webhook",
    secretScope: "environment_secret_manager",
    owner: "Hydrological Services Department",
    manualFallback:
      "NADMO regional desk confirms river level bulletin by phone.",
    updatedAt: now,
  },
  {
    id: "nadmo-alert-sync",
    partner: "NADMO National Operations",
    domain: "alert_sync",
    direction: "outbound",
    status: "mock_contract",
    cadence: "Near real time after human approval",
    freshnessWindowMinutes: 5,
    pii: "aggregate_only",
    authenticationMode: "signed_webhook",
    secretScope: "environment_secret_manager",
    owner: "NADAA platform operator",
    manualFallback: "Public alert publication continues inside NADAA workflow.",
    updatedAt: now,
  },
];

export const fallbackAlertRules: AlertRuleSummary[] = [
  {
    id: "rule-alert-approval",
    name: "Mass alert approval",
    scope: "District, regional, and national alert publication",
    targetType: "district",
    severity: "warning",
    status: "submitted",
    approverRoles: ["system_admin", "agency_admin", "nadmo_officer"],
    emergencyOverrideRoles: ["system_admin", "nadmo_officer"],
    mfaRequired: true,
    auditAction: "alert.approved or alert.rejected",
    lastReviewedAt: "2026-07-06T09:10:00Z",
  },
  {
    id: "rule-emergency-override",
    name: "Emergency override",
    scope:
      "Immediate life-safety warnings when normal approval would delay action",
    targetType: "region",
    severity: "emergency",
    status: "approved",
    approverRoles: ["system_admin", "nadmo_officer"],
    emergencyOverrideRoles: ["system_admin", "nadmo_officer"],
    mfaRequired: true,
    auditAction: "alert.emergency_override",
    lastReviewedAt: "2026-07-06T09:15:00Z",
  },
  {
    id: "rule-national-target",
    name: "National target reserve",
    scope: "National alerts must remain rare and life-safety scoped",
    targetType: "national",
    severity: "severe_warning",
    status: "draft",
    approverRoles: ["system_admin", "nadmo_officer"],
    emergencyOverrideRoles: ["system_admin"],
    mfaRequired: true,
    auditAction: "alert.target.previewed",
    lastReviewedAt: "2026-07-06T09:20:00Z",
  },
];

export const defaultUserForm: AdminUserFormState = {
  name: "",
  email: "",
  phone: "+233",
  agencyId: fallbackAgencies[1].id,
  role: "dispatcher",
};
